### ISSUE TITLE
header does not compile

### ISSUE THREAD

**Issue by adomasbaliuka** [riidefi/smol_json#1]
The header does not compile, neither using C++11, C++17, C++20, on neither Clang nor GCC. Since the header is so small, the compiler error messages can be explored on [godbolt.org](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGIaa4AMngMmAByPgBGmMT%2BAOxmpAAOqAqETgwe3r7%2ByanpAsGhESzRsZIJtpj2jgJCBEzEBFk%2BftJ2mA4Z9Y0EReFRMfGJCg1NLTntY30hA6VDFWYAlLaoXsTI7BwA9ABUJhoAggcAnAosngD62goCB8caJ7sA1IfPaUb0ALQImExYZGejgYAE9SM8GAIvmJaKhRMDgODRsQ/mx0M8AFJCADyYWeSUaSmIz1oeEixEaIOe/GJFwBDGebmszKOpxeABFOph5sSzBouCdwcQ8HgsDR7vdOTRQgoQBLHl9nkIALLYwKXLG4y7s7AWOQAcTlrMebOeUtmQIQeAUQNQz0YTEi9GeTAURNqDAUADp5Q8ToqVWqNTiwpdDhZsQAlAAqEBYCmASyNftN5tClut1JILueXiJLsiJAI1K8DC6Ah9xpOprcMMw6IA7r8GYH1ZrQzq9frnpmxbN0YYBwzXe6MtSmHRvb7TgHVW2Q5dAtj9ZcAGJhOMJ8FendJ%2BXVx4czDSzAZm00nN5mIk1DAEtlj2VlOH57Yhi0KmiWj0RvNpVz4MtU7A0extPtQnQJ9TlTY8mC8WgCBtIh8WFQQqGeBtCAQZ42DdJhgFPJIURoVRnnMMwTAAVgsc4rhuO5KPZcioKrWcg3bS4hGjSMAEkwhXAA1HjsAAdWTaCXzTU8CCtJC7VGdAQBAZEQmAS4ADc8EwBttj%2BUZaCUlSjA0rSGxYg8njNWD4MQ20e0EGJmFoHsWCSeg2EEJgPXeC5aGuW4/GUghULUzTtOnI5sFUVg3MwWV9xeDxPWCrwuiMHMCWIIl91OWi/PowLlEJa9MqJCAFMM4LVJM7SIHIqiLGeLhwTMMjGPIpYlhMABmKxjT9F4iqy1ScyM4AvgAa0wEF62eVBIm0ToCHEk1Hm2bYyLiRryJCAhMAI4hLimkFyJAZ5JESMizDMQtPD%2BBgjum07x1oJRNqYqtTlu5yFFSzY3TI7r2XxYriC9MaAGlpp4vbiDq6jzAANio9kIDg5DjqWTa%2BufCy8HQiBjsBpigausxdv2mJHpO66ruRsxEZBrKYi9TBVCSJaeMECBOpy1aLKI3aqDq66KYO6nQKuyi8CotwGHI8FSpZgiCC5ggea63q%2BYs6o3vx55Cem4meuB8jvvu6nyLppGmaJVn2aWixUE8DXtYkk5BbQkWbud%2BhDAlzNzEohRZfl67FdBr0Vadl2sZ61cydxK2zvI7FV1XDqepx93Tl108UQIdYGSoMQlCziKLNOAui6BYgvEwcvPpNOJ2U17Oq0GwkRsMF1iApE6m5Oda2sar5mtr%2BvwRMLbnh3L13raj7ce%2B94/rim0TdtlnGn7mGYnhqwGZRiBdvsrBVDjra3cefWIDAMAlbBlF/mjVAJo155q%2BIYvS4brX%2Bpzo8T2BBhb1QRmYaWKMybghCOfNuFd3a30fl6a0atXaD3dsA0B10g4y0onLBWW8wYqzQbzf%2BuNc6vVPEgyO1oY60HQRQ/mWDvZBxDvgsOl1kHR19jzQGCdU5hGTondOmdyGAJOHnHsBNkHWmxAtJajCJFV0wIXb%2BW9Li3DYJceai0HAQEfvAjBjw87Xwsl/BkLDyLYD7iQH0HCOrWwZi9Mu4jjEnAsRPP%2B7dK4tyMQ8Z8hw3AGDdHFFa/ofJ0QCpVEKNUGzhNNEIPArlnRjTiS5WKHkGjeQvKMQcYgBCYHMqaHiKTuSMFsgRUIwpkDPDQK5Ro1oBBzQ5hSIgWUXTAAnMlF0oI6khKQggLyGT3IVLAl5JgfDBwkkYMAGSPMWJ%2BkVHlfyzgQD1GfiwBJL4kllPeMFVEzxIiulms0pg%2BzYlhTMhXZZvlVmBVflNPw2sXhvDSHsogTygQgg5sUl8Ik/zP3QOCdSYh642kaKeSExZkB%2BxROiZJaI8BeWqCCM6QLu4XO7gwdEMlGA5jQLCBkmFvz7LoM5KamAkiWlPGNZ4oLvBFJuZE/K0SQCBDZvvFZBUlKPMYEiO5PL1kHNYHuQeLxdmxUxCGGZqgWaMnWCiQQH5njoFQHFCEqBiy/SSCkJo1JYReRGikU%2B6AJmLJnCy%2B5SkhplW5WyjlcriBitxhK5JUr2xEPsrDEumw/mWSkjaPSVJCAxCNepU8hxlA8RDkcXY2xpxmG6kRfCLBzkCE2Im7qIRYVeCwIDNwCldpegQD1bAEok05u8PmnqbhkBjTLVm/GOLjz/nYguJcK51wVuzWWatp5a1FtQCWxtrIk3gVPK2QCoZO1rg3PGREs9dwoSFqw6i9qGKm1pgu8ElxLgCUOGGSM%2BohB7q6mO7qrh8ZNqoC29CU6OJcV4vxfdwkRK%2BmYLhAkmwrUFWxr6ZEqVtVVWMlciUV8qxpKuRANAPTkBDOIC8BQ4IvC7W6mYS4xZaDntxmdZE5UVgzIYBAbDOUr4t33FB0yMGBCjDqQhpDOH3Z4eCgR8E9BiPIg4wRpjzcrAUYATfd8FpYN0fg40F4ZqGh8NE8WaejVPHIizu9fcIRSTplQ4IdDmGiNzIQDJ2jcmZ6eI48p6eS8JJ%2Bj2iklFtaCA/IdGwZ40ZR1%2BhXqgVpXkSAmxNjRnpLnnHEAQAoLGsmyM%2BNOLfIL3oON6b4ffTesX5mdU/qomuJcqGN1xp4tgLBkCuQgNFr0UnJmEZKzzdjszkv%2BOggJqz3I3K2e6m4ezHNP2nhc91ctVZ3OefaQloGfm6MBcZtF0Lhnwva08ffDzYb2k%2BcG2NrLtWl6C1BXtcJsn6MSYuctx4mmCDaaw4wZbFG3HHDq%2BYbqE623zi1E%2Bvigk32/rZVR8KF6r1UBvXe2706wwRhjD2/GYpniXBEnxdDPabsPoXOGKMsYvJYxksQVADYXQEB7aYi90OAIcThzGNGBAmNJs%2B5jnF17BPHErVQEHMOgK6gNFD48FohAiTXIcHigRyrBSxmq1cE4GFpAAF6YFQMLZEccuvPD5PwtqTIMHXX6CnWmgQ%2BLYE4txR7zwU74Ldor2YyvWqq7COrh7/EyYW4l5jzL2PmfplZ%2BzznEA55Ywy2XD75Ovu25PEqNn2AAAayhsBuFjGzIiWMIBh%2BJNPJkcQ3C%2B8d1zq6l72bOuJ9du3k6/dhCEHISM2BI%2Bp6xrfe%2BDuA9B5D4X8PWNPFu%2B8Te2nuOFzAX1PcNTFoV584F0NmFDH0dMYg36OnoZ8cI6J3tk4w/FzLjnd7B3q4OeBGV8HUOhDEcT9r7/U7FmSee4/awOK37aWCoCv%2B/qw9owbNUgJUyOE8zFndaMwQqqJlTJxbp5LvT0TRDqR5kEjp6B7hh5OQ0hgAIIsxiQ9ICADIgpLlTJtgKpYDqowMjhh4N1Ao3s0chkbRoh8UiJUBNIsB0RckGgcUCl0xH9ylPIPRY1DhAMHAlQRUWBwMfENlUQIAp8zcntRIsUjAsZIQ2ZNgkgMdB4zpjklBucQpCNkB1hbg4YxpitX9eZPpyMLNVo/R290wttxNEMjl9oQg%2BEBDVAhCjMFM0t1FxCilys24VMqxNDTxtC%2B9XBDD1VjCqVTDUs1EGRLDWYcUeYzNLshN1NTwV5rRsAxcT5n8xcQtNVBD3DsZPCa4ZCspsxrA5oqAN4utN4fDnCbDzM%2BYNDhN0wV4FAmAqBMAuZkBIjixoj%2BDXCTDJtB5b4wiIjajeNfEIt%2BZki5DiZ7Q/Cat%2BYVEvCXF68MFAjK5B5ujUjLBN5oizNB5PEUpRiUxxj7DttiQVZ/CVDOiThmiFBwjhYNBlCmEPFzCGQNBVAqAvs3EJjcZHDGg6lejdgpjiAJ9coyiKiywIAuABjzEzi6k3jxjVMiiHDDN1iXgVZlBWNL4zDhiXiAi1CDxCjgj1j8RMBMB35T45igYfjGjcY9iDiIA2jEj1ELiri9tst/jdgYNZDpjGpajAS1DDg1sUVNswSdCXh4SbjODNcX0hIeDLDt8KT7hGAfB%2BkRxnM35GBowHMWD9wwhClSB9xsQ2t5E9ECAlSqxglUhMA1SlpNSAlTgVTGBDg%2B4mAwR9xtSlBTT%2B4DT9wr8jA7THg1YnSThVxDUNTnh1oBt485BPQvBdUix6wK4PAWA01XSsgBAnS/R6FozThlQmBVBwMSZ25DhYUJS%2BV5ZWRB9TgqBhRXBxSAZHUYgsskgvAnQ8BkBwk1jQiFAZSOYIBMz6zTwtVfhnVf9ko8T3ZFjjZSZWySybj8i7CQTJSnlmzngVZmyDNOztipt/iMdBzViRzayFTQhpy6N5MSSGRrQpymyHMlJVzMA8ilyUTazjSGA9T9FxselNzPEdyHNGypSGBmylJzzLzx9epbDkSO9fZQIrTdSFEryOyNzjN/j7yGy9yOYlJ/z3zjzESazfy5E2sbTzT1yPC7y6yHzIL2AQBzyUKQQ4LgTTzEKFB/z8K0KEiMLdynyXyQAyKzSCKESiKfzPBQIHTgAKLbywLMKIKaL9zhUpCmLhziLWLUFuZryQLYSa5wLMBHyxz%2BK1ZCLhKWLnJrR3TUAvJOLQLhiZK5LpT%2BL1L19PyhzvziiSLQy00tKpL1FdLsLoLUAwymAlLTKQjzLPABArKtzQJqL5KoK6L3KGBnLItlySL6FPKqKsK%2BK/L6EgrlL7cm97teTuCRIJzVF2Lwr/iG1jKTyLRT4SFxLgL0KwKhKXKjlfyeFY5CrKL/jIgSr8C9oHB6xwlsKgQJ8eTn1kreDgBhShMH8J8qAPTqQJ8V5arxEztUz0yizOViQzoyyKzak2DWBFZyzSRalMyvSNoklPhpInyLlUQ5Sjg5rVq2Tkoo8yrRKFAAVQ0hAj8YMEM6kJKRCVidjPFHiFtgYwAOBnhPrnhNpY95cTjThal3rvqOBQ4fqY9Ib3EgbeyPqwb8ECAIa48obAbHhgagZN5PrZZiAsbFymTgqUSdD3gJo8AkgRIFAXC4jhCuz%2BYCSIijj2juz/iyTridjtYiaaAso5NSZNjfjczsw6pPzrQrq9obqmBNhqA8AuabDOaNyebVElFBib4CYWjDjjjlFHhPEWaeq/jhjZaFyItAj6sbM9pa0ibkBwQWrWs/5utSqV4w8lpJV6BKa3DqbZzJj7r9beiFASayaKa%2BblaDYvaQaWbGb%2BZN9MtztEECZg6MbSZkAw7qwcylaThubgZra3jw75y65lic4jama9at88aK4ELWKHaHA8KGKXaTDqrhjy7hBKDa0sbqJPrLaoqcLK7%2B4y1/Dsr4KQqy6HYHB6L%2B5q74iuK67B6G6ykm74b2RW7Rz9K/Lh7zTu7Yrdj%2B7nJ663zAL1Y6iqaiqJ6OYHAna/43Asatp567LcLVSd7V6SqCaVL7RJ6YKd7R7hDa6a566T6Z7zNL727oLYQlB3y77e7mKzKB6j7mgHLLK97XaD7P7J7v7mtW6/7fKcKLKmAQHtocrwHN7n6Aq374H1Ev7G7kGOBwBeAF7nz%2BLIz5Yuse7sG%2B6RLVKFA0EOapbRhYGa7x6a5JaubAZy1SZPqNAIaj5nFY6mQhGOAThPrL5/rqQOG07MaOAvhcbGGCiH7cGt42HPbFG26nkXhPleiGB4JaBhDnUaa8YCZ75Pkkc35eiZJrQdbItrGwAxL1Z9b1aU6I7XFUz3ZPkvgy006qHaK1ZM7U635Amus8BeiNBnHHgLwe9wS3r5aCAoS4Y45LAg7FHYbQbVGvr45ngNBtdngx4bD0b49cizMZjLAE63Zk6JjdiCZniBHlGRGCmxHGYWna1lGZGOBE7as2b%2BYAmy0YnN4RnonngXguBim0iWnFRhG1GzETKJEsdAaGmJFh4FTixzl8BgBCBwRIgvBgNyV7I9rWBlnHgy9A9g9YxSjyjKiYNSnUq0noSyE/GU6XHsn%2BGQbPr8m7GJoonsAYn9hSYx54nGnFic7wmVt6nETThh5sAW1v8qRsA04zo6DfonMUoywjU7hBNdb0si7DamHH6lZ0r2Gub9HGBDH7HN4THvxzGuH3DLGvm74wBbHbQJoHHZIIXb4vaBs4bZZyJZGzEfHc6lbcYJnsBgmr72Lwn7jdDoh9mGRN5IToSIXEnzbejeblNalBWinLjWaUngZeaBmNnaaCZ0aSYhXddrpRXoaLXGnpW6VN5NzlWQgUN0NoBVF0m%2BFFQPWGRFQfiVNBzvHs764YXm54Xo25zC7I6SWwHXLWKlYwrKXRhqWGBaWJoTYGWzGedYi4HWXA72XOWjHxneWo7LXvm5abXQbEb%2Bn6mhmmmDYOYMSIAjjcnPqcaOn6ZkZoagF0T34Q3fmOAvBRG%2B3LmPYh2IBlgu2OBMAHX1nm33iHmvjuoA7nXImgneir76Eo2LJpXIgHHoWq3Gmhia4liD2VnBigSS3Y663PqqAl287m2kEZ3O3R2mAJ2kYp223h3JdH2OBaAf2j4B3p32253R2FBQP%2B3UaIP34N353F3G3HWV3Hh7nPiqjJBN3/Hd3/6QB92w3Gnj3N468IWC7L3T2V272k6Y3Tj43fGyN8bHhrNGtTbmtrb2tnNXNNHk28HIHQzYpVBGzqRGanX03gmfbSbyaGHtZ%2BWcmQ6jWBnNb/jyPiPa8%2BHOHGSS6N6n7IHSEP7iH8GykROGpf3GI7qHiE6jPLFio2G4K17S6BPHaQMOKYSvL66hP6AzPwFkZLPzaPPPFyW3OYNHP76gjH766wqgv/ivOHLhOD4LPUZAvbOt403wvQGCXnP9PXOQooYQQ%2BEeHjPIH0rMm%2B3cuh6CG179wV4gVHk9Ks2uXjHTHzHDnfylAMTjlkBuWyPf5xOdiS8OW34AWeWnGz3coUoGCVThAh2LBxac2xjm2ZuhA5uFuOCmCbZkNzrnJ0AVOLIxCFuAzyoNhCMFANg2NVVUAYYIA9vlnVCzEAA/FbtbnrrY5dqd2%2BNVGGfb92c761o5I7pIa92jr6X877g2sxRa5g5xf7g96HwHnrgMmF8a7WF7jE%2Bbnr94SICAXYRx7bzriabriaAYu43Rn50maTv2uTgl04MvHPPPAvAVsATeUOiFhQTCAgeDGt8fJb9mk5UG0gT67ZQ97drrWVgjjBg9qFyN4j0QN6ZuiwYXsxaViXtB185Chi6XiNiViyeX08Zuue8hlXsXmV/D9XuiwBzAfC7X4Yq9uXgX8%2BpX439xVX83xejum%2B9U23qj2XnY/X0G3%2Bl3k4t3zeK%2Bl%2B734ji99Re3/3x38h5X1303tXj3%2ByolH3mP6j/nhXjgBtkXgPp9xPk44L4qMK/W8EWxhV%2BP4V%2B14PiREv5mdK8vrlzdgvjgdp/P%2BPrgIv92NvswHvro%2BP7qAfvX%2BPyQEfoG%2BPyiCftG%2BPxGGfk4NvuIBftvgADhX/j76c75z/yZF%2Bj7s%2BZjQWb8r%2BI7FDggQj38eHJD%2BBzaj/zqzuGPn0X29lrAYE%2BuLCBS5cYB9Guj5vv5OGLJwx2qj2V9DwTu6iFGCmyW7gNxWao9%2Bo9BYsLamvCzUVqlZZ4IAIOp%2BgkBQAhKqGC4KgCUqIWbWGdEAEEZJs//YeKuBIBsBiAKqdsOxQK57xXiVYNjgYA44tYHM3HTrLbTB6sVIY0MWGKJyoAwDB49PXPPnirxLRt66pV2MRybB0BTwhWP4OgAa5eMOiZiDnoQG54%2BsCAU5NQa%2BzMQB85WbnS/lYwNj3x4uRKRWuewf41wn%2BTuaxJPVmjnJCUFYMRB8xsEtt2WwsFWGV30GfNVOj/NnAvgcHXRFA14cWjkgFz1gf%2BywCjvzGv5MBb%2BzbIwZLyt7vlTB%2B/LxAe1SEW8MGmQtGrIBCB%2B8zEZ/GyAUIY52Dghz/ciFzAZSigv%2BDAWIbh1jZjEWOhLdRPYK5zkQ/SABHaqln%2BCND3BzHDRiwIaxsDT6XHA/DxyyI9ZfyO8c0kwKEEiDcYYgxnpIIrqa8R67zBBAkwFqnwxmpMOJp%2BWFh4A8iNTCwGcKbZQ9s84ggvPVzfiyCPBf3TntoMnIPl/B6g9xLkNT7%2BVHKFQ2DMCBKHfCBe4fK3vhQqEy9de7sMoRfynaeIuh3sP0vXVmifJv%2Bwwx1vRxvYdCWw1Q0IWYHCHEhIhY4EuAoMggYiViFmOAYaRbgbUIQB%2BBQEfhez4tDg/TfQJwEoi8A/A7fXgKgE4BMgLh7wNYBsAHRJoeApAZaDyM6ikAJo/gRGF6BmYnBEYiMDQJRDiCSBJAXACBN1HZEcBJAvALZDMw0CkBuRWgUgHyI4C8BZQxoyUVoBWBwBYAMARACgAS4KCyAFAGjK5DdEgBgACgZgEkAUAIAtUpALAJpE2A35tI55TgOKJoAIQYgsoCAJEGjG8BIgIQSkMmNICpjmAxAEEBkJ5GkB6kWSN8B%2BAzFYA0021TQLwHwAogugEaWUNwF4CcoZCG2fMRTAMj5jSQ5ISkB4CwCViJRwoLZA2JWADV8ICgCMQ2CjENiZAggEQGIHYBSBpx8gJQGoD7G6BmoBgIwCgGZCWB9AZIWUJABWAeYaCnAL4ApBNimALhXAOIFaOqBLQMgLgHFBMD8DNQggswEoGUD0ApA0gHoJ8Z%2BPyAeh%2Bg74oYM1A6DlgGAPQcYJ4FaB6BQJHoCCTMGKCDBYgIE6YL%2BJQm9BAJSEiQCsFuDrBNg2E3UZyJNF9iLRzwVQKv0RhfBEYkgCcsgFqQQAcWJPA2LgEIDTFuoPxXgLaP6YrBZRlESQF6A0DdQNRZgKQJIDVGIwRJq/SiLqP1GkAtkq/ASVJJmaIxuoq/MwCcDiCr8Eg0gU0byM4BWiQANoysfaKdEQAkAawAgGWQ1Iej6kSQN0WEAPycByJlE6ibRNqRaivQZgRsfgHaSig9A/AGcV%2BHnHSAApS4lQOoHzFrjSADYCkEkGTErB2xRE3SeaM4DYhjmVk9ImRIolUSaJwAOiQbEYkR4hObo5PBxIlHGSVgvwf4EMAqztjZJWyE4FwC9CNTJAq/E4N1ERhXiNAIkswKv2In5iLRBkoyVKJ4kgBKI3UL0G1MEndQTgF0SiJRC0mtTdR3ULkSRP0nlSRpuoryf1LNGDSNpdolYBGmGjOBJAQAA%3D)

**Comment by snailspeed3** [comment]
Thanks for pointing this out. Should be fixed now.
